server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap:9093
    consumer:
      security:
        protocol: SSL
      ssl:
        key-store-type: PKCS12
        key-store-password: ${DEMO_KEY_STORE_PASSWORD}
        key-store-location: /tmp/ca.p12
        trust-store-type: PKCS12
        trust-store-password: ${DEMO_TRUST_STORE_PASSWORD}
        trust-store-location: /tmp/user.p12